-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.admin_id_seq;

CREATE SEQUENCE public.admin_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.barang_id_seq;

CREATE SEQUENCE public.barang_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public."admin" definition

-- Drop table

-- DROP TABLE public."admin";

CREATE TABLE public."admin" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username text NULL,
	"password" text NULL,
	CONSTRAINT admin_pkey PRIMARY KEY (id)
);


-- public.barang definition

-- Drop table

-- DROP TABLE public.barang;

CREATE TABLE public.barang (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nama text NULL,
	harga text NULL,
	stok text NULL,
	foto text NULL,
	CONSTRAINT barang_pkey PRIMARY KEY (id)
);


-- public.pendaftaran definition

-- Drop table

-- DROP TABLE public.pendaftaran;

CREATE TABLE public.pendaftaran (
	username text NOT NULL,
	nama text NULL,
	"password" text NULL,
	telepon text NULL,
	CONSTRAINT pendaftaran_pkey PRIMARY KEY (username)
);


